# Generated by Django 3.1.4 on 2021-01-03 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210103_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
