# Generated by Django 3.1.3 on 2021-01-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210105_2208'),
        ('quiz', '0005_auto_20210103_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='account.company'),
        ),
    ]
