# Generated by Django 3.1.4 on 2020-12-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201218_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cip',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
