# Generated by Django 3.1.3 on 2020-12-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_company_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
