# Generated by Django 3.1.3 on 2020-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201221_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
    ]
