# Generated by Django 3.1.3 on 2020-12-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_company_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_image'),
        ),
    ]
