# Generated by Django 3.1.3 on 2020-12-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201222_2105'),
        ('account', '0008_auto_20201222_2108'),
    ]

    operations = [
    ]
