# Generated by Django 3.1.3 on 2020-12-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20201221_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('work_time', models.CharField(blank=True, max_length=30)),
                ('job_description', models.CharField(blank=True, max_length=500)),
                ('qualifications', models.CharField(blank=True, max_length=1000)),
                ('benefits', models.CharField(blank=True, max_length=500)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
    ]
