# Generated by Django 3.1.3 on 2020-12-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20201222_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
