# Generated by Django 3.1.3 on 2021-01-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applying_position',
        ),
    ]
