# Generated by Django 3.1.4 on 2021-01-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_merge_20201223_0304'),
        ('job', '0006_remove_jobapplication_applying_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
